import * as Ladda from 'ladda';
require('./bootstrap');
window.$ = window.jQuery = require('jquery/dist/jquery');
require('bootstrap/dist/js/bootstrap');
require('select2/dist/js/select2.full.min');
require('../plugins/reflow-table-master/reflow-table');
require('jquery-validation');
require('jquery-validation/dist/additional-methods');
require('jquery-expander/jquery.expander.min');
require('jquery-reflow-table/dist/js/reflow-table.min');
window.Noty = require('noty');
window.Ladda = require('ladda');
window.Swal = require('sweetalert2');
require('flatpickr');
require('./admin/gmx.min');
require('./admin/custom');
require('./admin/designer');